# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/zoonipy/',
                'doc_host': 'https://michaelaye.github.io',
                'git_url': 'https://github.com/michaelaye/{lib_name}/',
                'lib_path': 'zoonipy'},
  'syms': {'zoonipy.core': {'zoonipy.core.foo': ('core.html#foo', 'zoonipy/core.py')}}}
